#!/usr/bin/env node
/**
 * scaffold.mjs — cross-platform multi-harness plugin scaffold renderer.
 *
 * Single source of truth for plugin generation: renders `templates/shared/`
 * plus each requested harness template under `templates/harnesses/<h>/` into a
 * new target directory. `scaffold.sh` and `scaffold.ps1` are thin
 * argument-normalizing wrappers around this file.
 *
 * Template substitution is function-based (never shell/sed syntax), so
 * user-supplied values containing `/`, `&`, `$`, backslashes, Unicode, or
 * newlines survive byte-for-byte. Output files are written as UTF-8 with LF
 * line endings.
 */
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const TEMPLATES_ROOT = join(REPO_ROOT, "templates");

export const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
export const HARNESSES = ["claude-code", "pi", "opencode", "oh-my-pi"];
export const DEFAULT_HARNESSES = ["claude-code"];
export const DEFAULT_DESCRIPTION = "A plugin generated by plugin-factory";
export const DEFAULT_USER_LANG = "zh-CN";
export const SCAFFOLD_VERSION = "0.1.0";

/**
 * Validate scaffold options. Returns an array of error strings (empty = valid).
 * @param {{name: string, prefix: string, target: string, description?: string, userLang?: string, harnesses?: string[]}} opts
 * @returns {string[]}
 */
export function validateOptions({ name, prefix, target, harnesses }) {
  const errors = [];
  if (typeof name !== "string" || !NAME_RE.test(name)) {
    errors.push(`name must match ${NAME_RE} (got ${JSON.stringify(name)})`);
  }
  if (typeof prefix !== "string" || !NAME_RE.test(prefix)) {
    errors.push(`prefix must match ${NAME_RE} (got ${JSON.stringify(prefix)})`);
  }
  if (typeof target !== "string" || target.length === 0) {
    errors.push("target is required");
  }
  if (!Array.isArray(harnesses) || harnesses.length === 0) {
    errors.push("harnesses must be a non-empty array");
  } else {
    for (const h of harnesses) {
      if (!HARNESSES.includes(h)) errors.push(`unknown harness: ${h}`);
    }
  }
  return errors;
}

/**
 * Function-based template substitution. `$`/`&`/`\` in values are literal.
 * Unknown placeholders are left untouched.
 * @param {string} template
 * @param {Record<string, string>} values
 * @returns {string}
 */
export function renderTemplate(template, values) {
  return template.replace(/\{\{([A-Z_]+)\}\}/g, (match, key) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match,
  );
}

/** Normalize a template-relative path to a target-relative output path (forward slashes). */
function renderOutputPath(rel, values) {
  const normalized = rel.replace(/\\/g, "/");
  const noExt = normalized.endsWith(".tmpl") ? normalized.slice(0, -5) : normalized;
  return renderTemplate(noExt, values);
}

/**
 * Recursively list `*.tmpl` files under `dir`, returning { full, rel } pairs
 * with `rel` relative to the template root (stable across recursion), using
 * forward slashes.
 */
async function collectTemplateFiles(dir, root = dir) {
  const out = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await collectTemplateFiles(full, root)));
    } else if (entry.name.endsWith(".tmpl")) {
      out.push({ full, rel: relative(root, full).replace(/\\/g, "/") });
    }
  }
  return out;
}

/**
 * Build the substitution table for one scaffold run.
 */
function buildValues({ name, prefix, description, userLang, harnesses, validationScripts }) {
  const values = {
    PLUGIN_NAME: name,
    PLUGIN_PREFIX: prefix,
    PLUGIN_DESCRIPTION: description,
    USER_LANG: userLang,
    VERSION: SCAFFOLD_VERSION,
    VERSION_DATE: new Date().toISOString().slice(0, 10),
    VALIDATE_SCRIPT: validationScripts?.validate ?? "bash scripts/validate-structure.sh",
    VALIDATE_PS_SCRIPT: validationScripts?.validatePs ?? "powershell -NoProfile -ExecutionPolicy Bypass -File scripts/validate-structure.ps1",
    LIFECYCLE_SCRIPT: validationScripts?.lifecycle ?? "node scripts/verify.mjs lifecycle --format table",
    VALIDATION_INSTRUCTIONS: validationScripts
      ? "Run npm run validate (and npm run validate:ps on Windows) before committing structural changes.\nRun npm run lifecycle before any release.\nSee scripts/ for custom domain validators."
      : "Run npm run validate (and npm run validate:ps on Windows) before committing\nstructural changes; both invoke the same Node verifier.\nRun npm test (and npm run test:coverage) before any release.",
  };
  const bootstrapExt = `.pi/extensions/${prefix}-bootstrap.ts`;
  const hasPi = harnesses.includes("pi");
  const hasOmp = harnesses.includes("oh-my-pi");
  const fields = [];
  // Every field keeps a trailing comma: the template places {{PACKAGE_HARNESS_FIELDS}}
  // on its own line between "private": true, and "scripts", so each rendered
  // field must stay comma-terminated to keep the JSON valid.
  if (hasPi || hasOmp) fields.push(`  "pi": { "extensions": ["${bootstrapExt}"], "skills": ["skills"] },`);
  if (hasOmp) fields.push(`  "omp": { "extensions": ["${bootstrapExt}"], "skills": ["skills"] },`);
  values.PACKAGE_HARNESS_FIELDS = fields.join("\n");
  values.PLUGIN_PREFIX_CF = prefix.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

  // README install sections per advertised harness.
  const installSections = [];
  if (harnesses.includes("claude-code")) {
    installSections.push(
      `### Claude Code\n\nRun Claude Code with this plugin loaded:\n\n\`\`\`sh\nclaude --plugin-dir ./${name}\n\`\`\``,
    );
  }
  if (hasPi) {
    installSections.push(
      `### pi\n\nInstall from a git repository:\n\n\`\`\`sh\npi install git:github.com/<owner>/${name}\n\`\`\``,
    );
  }
  if (hasOmp) {
    installSections.push(
      `### oh-my-pi (omp)\n\nInstall from a git repository:\n\n\`\`\`sh\nomp plugin install git:github.com/<owner>/${name}\n\`\`\``,
    );
  }
  if (harnesses.includes("opencode")) {
    installSections.push(
      "### opencode\n\nCopy the plugin directory into your project — opencode picks up\n`.opencode/plugins/` and `.opencode/skills/` automatically (see `.opencode/INSTALL.md`).",
    );
  }
  values.HARNESS_INSTALL = installSections.join("\n\n");

  // install.sh lines per advertised harness ($src = script directory).
  const shLines = [];
  if (harnesses.includes("claude-code")) shLines.push('echo "  Claude Code: claude --plugin-dir $src"');
  if (hasPi) shLines.push(`echo "  pi:          pi install git:github.com/<owner>/${name}"`);
  if (hasOmp) shLines.push(`echo "  oh-my-pi:    omp plugin install git:github.com/<owner>/${name}"`);
  if (harnesses.includes("opencode")) shLines.push('echo "  opencode:    see .opencode/INSTALL.md in the plugin"');
  values.HARNESS_INSTALL_SH = shLines.join("\n");

  // install.ps1 lines per advertised harness ($src = script directory).
  const psLines = [];
  if (harnesses.includes("claude-code")) psLines.push('Write-Host "  Claude Code: claude --plugin-dir $src"');
  if (hasPi) psLines.push(`Write-Host "  pi:          pi install git:github.com/<owner>/${name}"`);
  if (hasOmp) psLines.push(`Write-Host "  oh-my-pi:    omp plugin install git:github.com/<owner>/${name}"`);
  if (harnesses.includes("opencode")) psLines.push('Write-Host "  opencode:    see .opencode/INSTALL.md in the plugin"');
  values.HARNESS_INSTALL_PS = psLines.join("\n");

  return values;
}

/**
 * Read every template under `templateDir`, normalize line endings, render, and
 * return a write plan. Output paths already present in `seen` (set) are
 * skipped — pi and oh-my-pi share the `.pi/extensions/<prefix>-bootstrap.ts`
 * path, so requesting both must not produce a duplicate.
 */
async function planTemplates(templateDir, values, seen) {
  const plan = [];
  for (const { full, rel } of await collectTemplateFiles(templateDir)) {
    const outRel = renderOutputPath(rel, values);
    if (seen.has(outRel)) continue;
    seen.add(outRel);
    let text = await readFile(full, "utf8");
    text = text.replace(/\r\n/g, "\n");
    text = renderTemplate(text, values);
    plan.push({ outRel, text });
  }
  return plan;
}

/** Copy every rendered skill under `<target>/skills/` into `.opencode/skills/`. */
async function copySkillsForOpencode(absTarget, files) {
  const skillDirs = files.filter((f) => f.startsWith("skills/") && f.endsWith("/SKILL.md"));
  const copied = [];
  for (const skillFile of skillDirs) {
    const relUnderSkills = skillFile.slice("skills/".length);
    const src = join(absTarget, skillFile);
    const dest = join(absTarget, ".opencode", "skills", relUnderSkills);
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, await readFile(src, "utf8"), "utf8");
    copied.push(`.opencode/skills/${relUnderSkills}`);
  }
  return copied;
}

/**
 * Scaffold a standalone plugin project.
 *
 * @param {{name: string, prefix: string, target: string, description?: string, userLang?: string, harnesses?: string[], autoVerify?: boolean}} opts
 * @returns {Promise<{target: string, harnesses: string[], files: string[], verify?: {ok: boolean, stdout: string, stderr: string}}>}
 *   When `autoVerify` is true, runs the generated project's own verifier
 *   (`<target>/scripts/verify.mjs structure`) and includes the result.
 */
export async function scaffoldPlugin({
  name,
  prefix,
  target,
  description = DEFAULT_DESCRIPTION,
  userLang = DEFAULT_USER_LANG,
  harnesses = DEFAULT_HARNESSES,
  autoVerify = false,
  validationScripts,
}) {
  const errors = validateOptions({ name, prefix, target, harnesses });
  if (errors.length > 0) {
    const err = new Error(`scaffold options invalid:\n- ${errors.join("\n- ")}`);
    err.code = "EINVALID_OPTIONS";
    throw err;
  }

  const absTarget = resolve(target);

  // Reject an existing target BEFORE creating any file.
  let targetStat = null;
  try {
    targetStat = await stat(absTarget);
  } catch (e) {
    if (e.code !== "ENOENT") throw e;
  }
  if (targetStat) {
    const err = new Error(`target already exists: ${absTarget}`);
    err.code = "ETARGET_EXISTS";
    throw err;
  }

  const values = buildValues({ name, prefix, description, userLang, harnesses, validationScripts });

  // Verify every requested harness has a template directory before writing.
  const harnessDirs = [];
  for (const h of harnesses) {
    const dir = join(TEMPLATES_ROOT, "harnesses", h);
    let st = null;
    try {
      st = await stat(dir);
    } catch (e) {
      if (e.code !== "ENOENT") throw e;
    }
    if (!st || !st.isDirectory()) {
      const err = new Error(`no template directory for harness: ${h}`);
      err.code = "EHARNESS_TEMPLATE";
      throw err;
    }
    harnessDirs.push(dir);
  }

  // Plan every file first (atomic: no partial writes on a harness failure).
  const seen = new Set();
  const plan = await planTemplates(join(TEMPLATES_ROOT, "shared"), values, seen);
  for (const dir of harnessDirs) {
    plan.push(...(await planTemplates(dir, values, seen)));
  }

  // Write everything.
  for (const { outRel, text } of plan) {
    const out = join(absTarget, outRel);
    await mkdir(dirname(out), { recursive: true });
    await writeFile(out, text, "utf8");
  }

  const files = plan.map((p) => p.outRel);

  // opencode discovers skills under `.opencode/skills/` — no manual copy step.
  if (harnesses.includes("opencode")) {
    const copied = await copySkillsForOpencode(absTarget, files);
    files.push(...copied);
  }

  files.sort();

  if (autoVerify) {
    const verifier = join(absTarget, "scripts", "verify.mjs");
    const v = spawnSync(process.execPath, [verifier, "structure", "--root", absTarget], {
      encoding: "utf8",
    });
    const verify = {
      ok: v.status === 0 && !/FAIL/.test(v.stdout || ""),
      stdout: (v.stdout || "").trim(),
      stderr: (v.stderr || "").trim(),
    };
    return { target: absTarget, harnesses, files, verify };
  }

  return { target: absTarget, harnesses, files };
}

function usage() {
  console.error(
    [
      "Usage: node scripts/scaffold.mjs <plugin-name> <prefix> <target-dir> [description] [user-lang] [--harnesses a,b,c] [--auto-verify] [--validation-scripts <json>]",
      "       node scripts/scaffold.mjs --name <n> --prefix <p> --target <dir> [--description <d>] [--user-lang <l>] --harnesses claude-code,pi,opencode,oh-my-pi [--auto-verify] [--validation-scripts <json>]",
      "       --auto-verify  run the generated project's structure verifier after scaffolding (exit 1 on FAIL findings)",
      "       --validation-scripts <json>  JSON object with validate/validate:ps/lifecycle keys",
    ].join("\n"),
  );
}

function parseArgs(argv) {
  const args = {};
  const positional = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    switch (a) {
      case "--name":
        args.name = argv[++i];
        break;
      case "--prefix":
        args.prefix = argv[++i];
        break;
      case "--target":
        args.target = argv[++i];
        break;
      case "--description":
        args.description = argv[++i];
        break;
      case "--user-lang":
        args.userLang = argv[++i];
        break;
      case "--harnesses":
        args.harnesses = (argv[++i] || "")
          .split(",")
          .map((s) => s.trim())
          .filter(Boolean);
        break;
       case "--auto-verify":
         args.autoVerify = true;
         break;
       case "--validation-scripts":
         args.validationScripts = JSON.parse(argv[++i]);
         break;
      case "-h":
      case "--help":
        usage();
        process.exit(0);
        break;
      default:
        if (a.startsWith("--")) {
          console.error(`scaffold: unknown option: ${a}`);
          usage();
          process.exit(2);
        }
        positional.push(a);
    }
  }
  // Positional compatibility: name prefix target [description] [user-lang]
  if (args.name === undefined && positional.length >= 1) args.name = positional[0];
  if (args.prefix === undefined && positional.length >= 2) args.prefix = positional[1];
  if (args.target === undefined && positional.length >= 3) args.target = positional[2];
  if (args.description === undefined && positional.length >= 4) args.description = positional[3];
  if (args.userLang === undefined && positional.length >= 5) args.userLang = positional[4];
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.name || !args.prefix || !args.target) {
    usage();
    process.exit(2);
  }
  try {
    const result = await scaffoldPlugin(args);
    console.log(`Scaffolded: ${result.target}`);
    console.log(`Harnesses: ${result.harnesses.join(", ")}`);
    console.log(`Files: ${result.files.length}`);
    if (process.env.SCAFFOLD_LIST_FILES === "1") {
      for (const f of result.files) console.log(`  ${f}`);
    }
    if (result.verify) {
      if (result.verify.ok) {
        console.log("Auto-verify: PASS (structure layer, no findings).");
      } else {
        console.error("Auto-verify: FAIL — the generated project did not pass structure checks.");
        if (result.verify.stdout) console.error(result.verify.stdout);
        if (result.verify.stderr) console.error(result.verify.stderr);
        process.exit(1);
      }
    }
    console.log("Next: author real skills via skill-creator (pf-build), then run pf-verify.");
  } catch (err) {
    console.error(`FAIL: ${err.message}`);
    process.exit(1);
  }
}

if (import.meta.url === new URL(`file://${process.argv[1]}`).href.replace(/\\/g, "/")) {
  main();
}
