#!/usr/bin/env node
/**
 * render-routing.mjs — regenerate the routing tables in skills/using-pf/SKILL.md
 * from scripts/routing-table.json (the single source of truth).
 *
 * Usage:
 *   node scripts/render-routing.mjs          # rewrite SKILL.md in place
 *   node scripts/render-routing.mjs --check  # exit 1 on drift, writes nothing
 *
 * The SKILL.md tables live between `<!-- ROUTING-PRIORITY:START -->` and
 * `<!-- ROUTING-PRIORITY:END -->` / `<!-- ROUTING-TRIGGER:START -->` and
 * `<!-- ROUTING-TRIGGER:END -->` markers. Only those blocks are rewritten.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderRoutingTables } from "./routing-render.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const TABLE_PATH = join(ROOT, "scripts", "routing-table.json");
const SKILL_PATH = join(ROOT, "skills", "using-pf", "SKILL.md");

const START_PRIORITY = "<!-- ROUTING-PRIORITY:START (generated by scripts/render-routing.mjs from scripts/routing-table.json — do not edit by hand) -->";
const END_PRIORITY = "<!-- ROUTING-PRIORITY:END -->";
const START_TRIGGER = "<!-- ROUTING-TRIGGER:START (generated by scripts/render-routing.mjs from scripts/routing-table.json — do not edit by hand) -->";
const END_TRIGGER = "<!-- ROUTING-TRIGGER:END -->";

function replaceBlock(text, startMarker, endMarker, table) {
  const re = new RegExp(`${escapeRegExp(startMarker)}[\\s\\S]*?${escapeRegExp(endMarker)}`);
  if (!re.test(text)) {
    throw new Error(`Routing marker not found: ${startMarker}`);
  }
  return text.replace(re, `${startMarker}\n${table}\n${endMarker}`);
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function render() {
  const json = JSON.parse(readFileSync(TABLE_PATH, "utf8"));
  const { priority, trigger } = renderRoutingTables(json);
  const skill = readFileSync(SKILL_PATH, "utf8");
  return replaceBlock(
    replaceBlock(skill, START_PRIORITY, END_PRIORITY, priority),
    START_TRIGGER,
    END_TRIGGER,
    trigger,
  );
}

const check = process.argv.includes("--check");
const current = readFileSync(SKILL_PATH, "utf8");
const next = render();

if (current === next) {
  console.log(check ? "Routing tables in sync." : "Routing tables already up to date.");
  process.exit(0);
}
if (check) {
  console.error("Routing tables drifted from scripts/routing-table.json — run: node scripts/render-routing.mjs");
  process.exit(1);
}
writeFileSync(SKILL_PATH, next, "utf8");
console.log("Updated skills/using-pf/SKILL.md routing tables.");
