#!/usr/bin/env bash
# scaffold.sh — generate a standalone Claude Code plugin project from templates.
# Usage: scaffold.sh <plugin-name> <prefix> <target-dir> [description] [user-lang]
#
# M1: Claude Code adapter. pi / opencode / oh-my-pi artifacts land in M2
# (the generated package.json already carries `pi`/`omp` fields for them).
set -eu

[ $# -ge 3 ] || { echo "Usage: $0 <plugin-name> <prefix> <target-dir> [description] [user-lang]"; exit 1; }
name="$1"; prefix="$2"; target="$3"; desc="${4:-A plugin generated by plugin-factory}"; lang="${5:-zh-CN}"

case "$name" in
  *[A-Z_]*|[0-9]*|*-*[a-z0-9]*-*) : ;;
  *) ;;
esac
case "$name" in
  *[A-Z_]*|[0-9]*) echo "FAIL: plugin-name must be lowercase with hyphens (e.g. my-plugin)"; exit 1 ;;
esac
case "$prefix" in
  *[A-Z_]*|[0-9]*) echo "FAIL: prefix must be lowercase with hyphens (e.g. pf)"; exit 1 ;;
esac

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmpl="$root/templates/claude-code"
[ -d "$tmpl" ] || { echo "FAIL: templates missing: $tmpl"; exit 1; }
[ -e "$target" ] && { echo "FAIL: target already exists: $target"; exit 1; }

# Empty dirs the templates don't provide
mkdir -p "$target/skills" "$target/commands" "$target/scripts" "$target/tests" "$target/docs"

# Copy *.tmpl → final path, substituting placeholders (skill.tmpl handled below)
while IFS= read -r f; do
  rel="${f#"$tmpl"/}"
  out="$target/${rel%.tmpl}"
  mkdir -p "$(dirname "$out")"
  sed -e "s/{{PLUGIN_NAME}}/$name/g" \
      -e "s/{{PLUGIN_PREFIX}}/$prefix/g" \
      -e "s/{{PLUGIN_DESCRIPTION}}/$desc/g" \
      -e "s/{{VERSION}}/0.1.0/g" \
      -e "s/{{USER_LANG}}/$lang/g" "$f" > "$out"
done < <(find "$tmpl" -type f -name '*.tmpl' ! -name 'skill.tmpl')

# Example skill so the structure validates out of the box
mkdir -p "$target/skills/${prefix}-hello"
sed -e "s/{{PLUGIN_NAME}}/$name/g" \
    -e "s/{{PLUGIN_PREFIX}}/$prefix/g" \
    -e "s/{{PLUGIN_DESCRIPTION}}/$desc/g" "$tmpl/skill.tmpl" > "$target/skills/${prefix}-hello/SKILL.md"

chmod +x "$target/install.sh" "$target/hooks/session-start.sh" 2>/dev/null || true

echo "Scaffolded: $target"
echo "Next: author real skills via skill-creator (pf-build), then run pf-verify."
