# scaffold.ps1 — generate a standalone Claude Code plugin project from templates.
# Usage: .\scaffold.ps1 -Name my-plugin -Prefix mp -Target C:\path\to\out [-Description "..."]
#
# M1: Claude Code adapter. pi / opencode / oh-my-pi artifacts land in M2
# (the generated package.json already carries `pi`/`omp` fields for them).
param(
    [Parameter(Mandatory = $true)][string]$Name,
    [Parameter(Mandatory = $true)][string]$Prefix,
    [Parameter(Mandatory = $true)][string]$Target,
    [string]$Description = "A plugin generated by plugin-factory"
)

if ($Name -match '[A-Z_]' -or $Name -match '^[0-9]') {
    Write-Host "FAIL: plugin-name must be lowercase with hyphens (e.g. my-plugin)"; exit 1
}
if ($Prefix -match '[A-Z_]' -or $Prefix -match '^[0-9]') {
    Write-Host "FAIL: prefix must be lowercase with hyphens (e.g. pf)"; exit 1
}

$root = Split-Path -Parent $PSScriptRoot
$tmpl = Join-Path $root "templates/claude-code"
if (-not (Test-Path $tmpl)) { Write-Host "FAIL: templates missing: $tmpl"; exit 1 }
if (Test-Path $Target) { Write-Host "FAIL: target already exists: $Target"; exit 1 }

New-Item -ItemType Directory -Force -Path $Target | Out-Null
foreach ($d in @("skills", "commands", "scripts", "tests", "docs")) {
    New-Item -ItemType Directory -Force -Path (Join-Path $Target $d) | Out-Null
}

Get-ChildItem -Path $tmpl -Recurse -Filter *.tmpl | Where-Object { $_.Name -ne "skill.tmpl" } | ForEach-Object {
    $rel = $_.FullName.Substring($tmpl.Length).TrimStart('\', '/')
    $outRel = if ($rel.EndsWith(".tmpl")) { $rel.Substring(0, $rel.Length - 5) } else { $rel }
    $out = Join-Path $Target $outRel
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $out) | Out-Null
    $content = Get-Content -Raw $_.FullName
    $content = $content `
        -replace '{{PLUGIN_NAME}}', $Name `
        -replace '{{PLUGIN_PREFIX}}', $Prefix `
        -replace '{{PLUGIN_DESCRIPTION}}', $Description `
        -replace '{{VERSION}}', '0.1.0'
    Set-Content -Path $out -Value $content -Encoding UTF8
}

$skillDir = Join-Path $Target ("skills/" + $Prefix + "-hello")
New-Item -ItemType Directory -Force -Path $skillDir | Out-Null
$skill = Get-Content -Raw (Join-Path $tmpl "skill.tmpl")
$skill = $skill -replace '{{PLUGIN_NAME}}', $Name -replace '{{PLUGIN_PREFIX}}', $Prefix -replace '{{PLUGIN_DESCRIPTION}}', $Description
Set-Content -Path (Join-Path $skillDir "SKILL.md") -Value $skill -Encoding UTF8

Write-Host "Scaffolded: $Target"
Write-Host "Next: author real skills via skill-creator (pf-build), then run pf-verify."
